/**
 * Analysis-related type definitions for the Tavily Kalshi Signals frontend.
 */

import type { EventContext, MarketOption, MarketSnapshot, NewsContext } from "./market";

/** Trading signal generated by the analysis. */
export interface Signal {
  direction?: string;
  recommended_action?: string;
  market_prob?: number;
  model_prob?: number;
  model_prob_abs?: number;
  confidence?: string;
  confidence_level?: string;
  rationale?: string;
}

/** Trading decision based on the signal. */
export interface Decision {
  action?: string;
  edge_pct?: number;
  toy_kelly_fraction?: number;
  notes?: string;
}

/** Report can be a string, structured object, or generic record. */
export type Report = string | { title?: string; headline?: string; markdown?: string; thesis?: string } | Record<string, unknown>;

/** Status of each analysis phase. */
export interface RunStatus {
  market?: string;
  news?: string;
  signal?: string;
  report?: string;
}

/** Complete analysis results from the backend. */
export interface AnalysisResults {
  run_id?: string;
  market_snapshot?: MarketSnapshot;
  event_context?: EventContext;
  news_context?: NewsContext;
  signal?: Signal;
  decision?: Decision;
  report?: Report;
  market_options?: MarketOption[];
  requires_market_selection?: boolean;
  status?: RunStatus;
}
