from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, TypedDict

from app.domains.markets.adapters.base import Venue
from app.shared.types import (
    Decision,
    EventContext,
    EventDocument,
    Horizon,
    MarketDocument,
    MarketSnapshot,
    NewsContext,
    ReportBlock,
    RunEnvMetadata,
    Signal,
    StrategyParams,
    StrategyPreset,
)

if TYPE_CHECKING:
    from app.domains.news.query_generator import TavilyQuerySpec
else:
    # Import at runtime for LangGraph type hint evaluation
    try:
        from app.domains.news.query_generator import TavilyQuerySpec
    except ImportError:
        # Fallback if import fails (shouldn't happen in normal usage)
        TavilyQuerySpec = Any  # type: ignore[assignment,misc]


class TracePayload(TypedDict, total=False):
    steps: list[dict[str, Any]]
    raw_state: Any
    metadata: dict[str, Any]


class AgentState(TypedDict, total=False):
    """Shared state passed between agents in the LangGraph graph."""

    run_id: str
    run_at: str
    venue: Venue
    raw_url: str
    canonical_url: str
    market_id: str
    event_id: str
    selected_market_id: str
    gamma_event_id: str
    gamma_market_id: str
    market_url: str
    polymarket_url: str
    slug: str
    horizon: Horizon
    strategy_preset: StrategyPreset
    strategy_params: StrategyParams
    event: EventDocument
    market: MarketDocument
    market_snapshot: MarketSnapshot
    event_context: EventContext
    # Market selection (when URL is an event with multiple markets)
    selected_market_slug: str
    market_options: list
    requires_market_selection: bool
    tavily_queries: list["TavilyQuerySpec"]  # Generated by tavily_prompt_agent
    news_context: NewsContext
    signal: Signal
    decision: Decision
    report: ReportBlock
    env: RunEnvMetadata
    trace: TracePayload
    event_description: str
    # Position tracking
    position_side: Literal["flat", "long_yes", "long_no"]
    position_size_fraction: float  # Current fraction of bankroll in this market
    position_avg_price: float  # Average entry price for current position
    # Configuration options
    config: dict[str, Any]  # Analysis configuration (agent toggles, limits, etc.)

    # -------------------------------------------------------------------------
    # Kalshi-specific fields
    # -------------------------------------------------------------------------
    kalshi_url: str  # Kalshi market or event URL
    ticker: str  # Kalshi market ticker (e.g., "INXD-25JAN17-B24999")
    event_ticker: str  # Kalshi event ticker (e.g., "INXD-25JAN17")
    selected_ticker: str  # Selected market ticker (for multi-market events)
    available_markets: list[dict[str, Any]]  # List of markets for selection UI
