# app/shared/__init__.py
"""Shared module exports."""

from app.shared.exceptions import (
    ConfigurationError,
    DatabaseError,
    EventNotFoundError,
    ExternalAPIError,
    KalshiAPIError,
    KalshiAuthenticationError,
    KalshiEventNotFoundError,
    KalshiMarketNotFoundError,
    MarketNotFoundError,
    OpenAIAPIError,
    ProphilyError,
    TavilyAPIError,
    UnsupportedVenueError,
    ValidationError,
    VenueUrlParseError,
)
from app.shared.types import (
    ConfidenceLevel,
    Decision,
    DecisionAction,
    EventContext,
    EventDocument,
    Horizon,
    MarketDocument,
    MarketSnapshot,
    NewsArticle,
    NewsContext,
    ReportBlock,
    RunDocument,
    RunEnvMetadata,
    RunStatus,
    Signal,
    SignalDirection,
    StrategyParams,
    StrategyPreset,
    TraceDocument,
)

__all__ = [
    # Exceptions
    "ConfigurationError",
    "DatabaseError",
    "EventNotFoundError",
    "ExternalAPIError",
    "KalshiAPIError",
    "KalshiAuthenticationError",
    "KalshiEventNotFoundError",
    "KalshiMarketNotFoundError",
    "MarketNotFoundError",
    "OpenAIAPIError",
    "ProphilyError",
    "TavilyAPIError",
    "UnsupportedVenueError",
    "ValidationError",
    "VenueUrlParseError",
    # Types
    "ConfidenceLevel",
    "Decision",
    "DecisionAction",
    "EventContext",
    "EventDocument",
    "Horizon",
    "MarketDocument",
    "MarketSnapshot",
    "NewsArticle",
    "NewsContext",
    "ReportBlock",
    "RunDocument",
    "RunEnvMetadata",
    "RunStatus",
    "Signal",
    "SignalDirection",
    "StrategyParams",
    "StrategyPreset",
    "TraceDocument",
]
